"use client";
import HeaderMoudule from "@/components/HeaderAdmin/Header.module";
import "bootstrap/dist/css/bootstrap.min.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import "./globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SidebarModule from "@/components/SidebarAdmin/Sidebar.module";
import "primereact/resources/themes/lara-light-indigo/theme.css";
import { ToastContainer} from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import HeaderModule from "@/components/Header/header.module";
import FooterModule from "@/components/Footer/footer.module";
import "react-multi-carousel/lib/styles.css";
import { StoreProvider } from "@/redux/StoreProvider";


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
        {children}
        </StoreProvider>
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="colored"
        />
      </body>
    </html>
  );
}
